# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-27 22:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogHW9',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('text', models.CharField(max_length=200)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now, verbose_name='timestamp')),
            ],
            options={
                'permissions': (('see_post', 'Can see post'), ('create_post', 'Can create post'), ('modifiy_post', 'Can change post'), ('delete_post', 'Can remove a post')),
            },
        ),
    ]
