# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-31 12:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone
import pgcrypto_expressions.fields


class Migration(migrations.Migration):

    dependencies = [
        ('hw9', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogColumnEncryptHW9',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('text', pgcrypto_expressions.fields.EncryptedTextField()),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now, verbose_name='timestamp')),
            ],
            options={
                'permissions': (('see_post', 'Can see post'), ('create_post', 'Can create post'), ('modifiy_post', 'Can change post'), ('delete_post', 'Can remove a post')),
            },
        ),
    ]
