# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-25 01:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SQLinjection', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='secrets',
            name='secret_key',
            field=models.CharField(default='secret', max_length=20),
        ),
    ]
