# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-17 18:55
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hw6', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2017, 4, 17, 18, 51, 54, 89468), verbose_name='timestamp'),
        ),
    ]
