# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-17 20:18
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('hw6', '0002_blog_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2017, 4, 17, 20, 18, 33, 850394, tzinfo=utc), verbose_name='timestamp'),
        ),
    ]
